Script started on Wed 04 May 2011 03:19:09 PM PDT
private/cmps012b: No such file or directory.
[fcarril1@unix3 lab5]$ valgrind malloc
==10678== Memcheck, a memory error detector
==10678== Copyright (C) 2002-2009, and GNU GPL'd, by Julian Seward et al.
==10678== Using Valgrind-3.5.0 and LibVEX; rerun with -h for copyright info
==10678== Command: malloc
==10678== 
0x4c30090-> {6, (nil)}
==10678== 
==10678== HEAP SUMMARY:
==10678==     in use at exit: 16 bytes in 1 blocks
==10678==   total heap usage: 2 allocs, 1 frees, 32 bytes allocated
==10678== 
==10678== LEAK SUMMARY:
==10678==    definitely lost: 16 bytes in 1 blocks
==10678==    indirectly lost: 0 bytes in 0 blocks
==10678==      possibly lost: 0 bytes in 0 blocks
==10678==    still reachable: 0 bytes in 0 blocks
==10678==         suppressed: 0 bytes in 0 blocks
==10678== Rerun with --leak-check=full to see details of leaked memory
==10678== 
==10678== For counts of detected and suppressed errors, rerun with: -v
==10678== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 4 from 4)
[fcarril1@unix3 lab5]$ gdb malloc
GNU gdb (GDB) Red Hat Enterprise Linux (7.0.1-23.el5_5.2)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /afs/cats.ucsc.edu/users/h/fcarril1/private/cmps012b/lab5/malloc...done.
(gdb) break main
Breakpoint 1 at 0x400567: file malloc.c, line 13.
(gdb) run
Starting program: /afs/cats.ucsc.edu/users/h/fcarril1/private/cmps012b/lab5/malloc 
private/cmps012b: No such file or directory.

Breakpoint 1, main (argc=1, argv=0x7fffffffe4d8) at malloc.c:13
13	   node_ref ptr = malloc (sizeof (struct node));
(gdb) print ptr
$1 = (node_ref) 0x0
(gdb) print p[K*ptr
Cannot access memory at address 0x0
(gdb) step
14	   ptr = malloc (sizeof (struct node));
(gdb) print ptr
$2 = (node_ref) 0x601010
(gdb) print *ptr
$3 = {value = 0, link = 0x0}
(gdb) step
15	   ptr->value = 6;
(gdb) step
16	   ptr->link = NULL;
(gdb) step
17	   printf ("%p-> {%d, %p}\n", ptr, ptr->value, ptr->link);
(gdb) print ptr
$4 = (node_ref) 0x601030
(gdb) print *ptr
$5 = {value = 6, link = 0x0}
(gdb) step
0x601030-> {6, (nil)}
18	   free (ptr);
(gdb) step
19	   return EXIT_SUCCESS;
(gdb) step
20	}
(gdb) step
0x0000003bd5e1d994 in __libc_start_main () from /lib64/libc.so.6
(gdb) quit
A debugging session is active.

	Inferior 1 [process 10691] will be killed.

Quit anyway? (y or n) y
Please answer y or n.
A debugging session is active.

	Inferior 1 [process 10691] will be killed.

Quit anyway? (y or n) e y
[fcarril1@unix3 lab5]$ exit
exit

Script done on Wed 04 May 2011 03:20:03 PM PDT
