Script started on Wed 04 May 2011 09:35:58 PM PDT
private/cmps012b: No such file or directory.
[fcarril1@unix3 lab5]$ mk list.c
+ for CSOURCE in '$*'
+ cid + list.c
+ checksource list.c
checksource: No such file or directory
   file "list.c": 1 errors: lines 0
checksource: TOTAL COMPLAINTS: 1
+ lint -Xa -fd -m -u -x -errchk=%all list.c
command line: fatal: cannot open  list.c: No such file or directory
lint: errors in list.c; no output created
lint: pass2 not run - errors in list.c
++ echo list.c
++ sed 's/\.c$//'
+ EXECBIN=list
+ gcc -g -O0 -Wall -Wextra -std=gnu99 list.c -o list -lm
gcc: list.c: No such file or directory
[fcarril1@unix3 lab5]$ valgrind list2 foo bar
==29939== Memcheck, a memory error detector
==29939== Copyright (C) 2002-2009, and GNU GPL'd, by Julian Seward et al.
==29939== Using Valgrind-3.5.0 and LibVEX; rerun with -h for copyright info
==29939== Command: list2 foo bar
==29939== 
==29939== Invalid write of size 8
==29939==    at 0x4005CD: main (list2.c:19)
==29939==  Address 0x4c30048 is 0 bytes after a block of size 8 alloc'd
==29939==    at 0x4A05E1C: malloc (vg_replace_malloc.c:195)
==29939==    by 0x400589: main (list2.c:16)
==29939== 
==29939== Invalid read of size 8
==29939==    at 0x400629: main (list2.c:22)
==29939==  Address 0x4c30188 is 0 bytes after a block of size 8 alloc'd
==29939==    at 0x4A05E1C: malloc (vg_replace_malloc.c:195)
==29939==    by 0x400589: main (list2.c:16)
==29939== 
==29939== Invalid read of size 8
==29939==    at 0x4005F1: main (list2.c:23)
==29939==  Address 0x4c30188 is 0 bytes after a block of size 8 alloc'd
==29939==    at 0x4A05E1C: malloc (vg_replace_malloc.c:195)
==29939==    by 0x400589: main (list2.c:16)
==29939== 
0x4c30180->node {word=0x7ff0007c1->[REMOTEHOST=oakes-41-231.resnet.ucsc.edu], link=0x4c30130}
==29939== Invalid read of size 8
==29939==    at 0x40061D: main (list2.c:22)
==29939==  Address 0x4c30188 is 0 bytes after a block of size 8 alloc'd
==29939==    at 0x4A05E1C: malloc (vg_replace_malloc.c:195)
==29939==    by 0x400589: main (list2.c:16)
==29939== 
0x4c30130->node {word=(nil)->[(null)], link=0x4c300e0}
0x4c300e0->node {word=0x7ff0007bd->[bar], link=0x4c30090}
0x4c30090->node {word=0x7ff0007b9->[foo], link=0x4c30040}
0x4c30040->node {word=0x7ff0007b3->[list2], link=0x400650}
==29939== Invalid read of size 1
==29939==    at 0x4A06D82: strlen (mc_replace_strmem.c:275)
==29939==    by 0x3BD5E46B68: vfprintf (in /lib64/libc-2.5.so)
==29939==    by 0x3BD5E4D3F9: printf (in /lib64/libc-2.5.so)
==29939==    by 0x400618: main (list2.c:23)
==29939==  Address 0x6c894ce02464894c is not stack'd, malloc'd or (recently) free'd
==29939== 
==29939== 
==29939== Process terminating with default action of signal 11 (SIGSEGV)
==29939==  General Protection Fault
==29939==    at 0x4A06D82: strlen (mc_replace_strmem.c:275)
==29939==    by 0x3BD5E46B68: vfprintf (in /lib64/libc-2.5.so)
==29939==    by 0x3BD5E4D3F9: printf (in /lib64/libc-2.5.so)
==29939==    by 0x400618: main (list2.c:23)
0x400650->node {word=0x6c894ce02464894c->[==29939== 
==29939== HEAP SUMMARY:
==29939==     in use at exit: 40 bytes in 5 blocks
==29939==   total heap usage: 5 allocs, 0 frees, 40 bytes allocated
==29939== 
==29939== LEAK SUMMARY:
==29939==    definitely lost: 32 bytes in 4 blocks
==29939==    indirectly lost: 0 bytes in 0 blocks
==29939==      possibly lost: 0 bytes in 0 blocks
==29939==    still reachable: 8 bytes in 1 blocks
==29939==         suppressed: 0 bytes in 0 blocks
==29939== Rerun with --leak-check=full to see details of leaked memory
==29939== 
==29939== For counts of detected and suppressed errors, rerun with: -v
==29939== ERROR SUMMARY: 21 errors from 5 contexts (suppressed: 4 from 4)
Segmentation fault
[fcarril1@unix3 lab5]$ gdb list2
GNU gdb (GDB) Red Hat Enterprise Linux (7.0.1-23.el5_5.2)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /afs/cats.ucsc.edu/users/h/fcarril1/private/cmps012b/lab5/list2...done.
(gdb) run foo bar
Starting program: /afs/cats.ucsc.edu/users/h/fcarril1/private/cmps012b/lab5/list2 foo bar
private/cmps012b: No such file or directory.
0x601090->node {word=0x7fffffffe78d->[REMOTEHOST=oakes-41-231.resnet.ucsc.edu], link=0x601070}
0x601070->node {word=(nil)->[(null)], link=0x601050}
0x601050->node {word=0x7fffffffe789->[bar], link=0x601030}
0x601030->node {word=0x7fffffffe785->[foo], link=0x601010}
0x601010->node {word=0x7fffffffe745->[/afs/cats.ucsc.edu/users/h/fcarril1/private/cmps012b/lab5/list2], link=0x400650}

Program received signal SIGSEGV, Segmentation fault.
0x0000003bd5e79a10 in strlen () from /lib64/libc.so.6
(gdb) where
#0  0x0000003bd5e79a10 in strlen () from /lib64/libc.so.6
#1  0x0000003bd5e46b69 in vfprintf () from /lib64/libc.so.6
#2  0x0000003bd5e4d3fa in printf () from /lib64/libc.so.6
#3  0x0000000000400619 in main (argc=3, argv=0x7fffffffe4c8) at list2.c:23
(gdb) ls[Kist
warning: Source file is more recent than executable.
6	
7	typedef struct node *node_ref;
8	struct node {
9	   char *word;
10	   node_ref link;
11	};
12	
13	int main (int argc, char **argv) {
14	   node_ref head;
15	   for (int argi = 0; argi < 5; ++argi) {
(gdb) list list2.c:23
18	      node->word = argv[argi];
19	      node->link = head;
20	      head = node;
21	   }
22	   for (node_ref curr = head; curr->link != NULL; curr = curr->link) {
23	      printf ("%p->node {word=%p->[%s], link=%p}\n",
24	              curr, curr->word, curr->word, curr->link);
25	   }
26	   return 9;
27	}
(gdb) print head
No symbol "head" in current context.
(gdb) bt
#0  0x0000003bd5e79a10 in strlen () from /lib64/libc.so.6
#1  0x0000003bd5e46b69 in vfprintf () from /lib64/libc.so.6
#2  0x0000003bd5e4d3fa in printf () from /lib64/libc.so.6
#3  0x0000000000400619 in main (argc=3, argv=0x7fffffffe4c8) at list2.c:23
(gdb) up
#1  0x0000003bd5e46b69 in vfprintf () from /lib64/libc.so.6
(gdb) up
#2  0x0000003bd5e4d3fa in printf () from /lib64/libc.so.6
(gdb) up
#3  0x0000000000400619 in main (argc=3, argv=0x7fffffffe4c8) at list2.c:23
23	      printf ("%p->node {word=%p->[%s], link=%p}\n",
(gdb) print head
$1 = (node_ref) 0x601090
(gdb) print *head
$2 = {word = 0x7fffffffe78d "REMOTEHOST=oakes-41-231.resnet.ucsc.edu", link = 0x601070}
(gdb) print *(head->word)
$3 = 82 'R'
(gdb) print head_[K->link_[K->link->link
$4 = (node_ref) 0x601030
(gdb) print head->link->link->link*head->link->link->link(gdb) print *(head->link->link->link(gdb) print *((gdb) print *(h(gdb) print *(he(gdb) print *(hea(gdb) print *(head(gdb) print *(head-(gdb) print *(head->(gdb) print *(head->l(gdb) print *(head->li(gdb) print *(head->lin(gdb) print *(head->link(gdb) print *(head->link-(gdb) print *(head->link->(gdb) print *(head->link->l(gdb) print *(head->link->li(gdb) print *(head->link->lin(gdb) print *(head->link->link(gdb) print *(head->link->link-(gdb) print *(head->link->link->(gdb) print *(head->link->link->l(gdb) print *(head->link->link->li(gdb) print *(head->link->link->lin(gdb) print *(head->link->link->link)
$5 = {word = 0x7fffffffe785 "foo", link = 0x601010}
(gdb) exit
Undefined command: "exit".  Try "help".
(gdb) quit
A debugging session is active.

	Inferior 1 [process 30030] will be killed.

Quit anyway? (y or n) y
[fcarril1@unix3 lab5]$ exit
exit

Script done on Wed 04 May 2011 09:42:57 PM PDT
