# Makefile.deps created Mon Oct 28 11:04:40 PDT 2013 by make
astree.o: astree.cc astree.h auxlib.h stringset.h lyutils.h yyparse.h
lyutils.o: lyutils.cc lyutils.h astree.h auxlib.h yyparse.h
auxlib.o: auxlib.cc auxlib.h
stringset.o: stringset.cc stringset.h auxlib.h
main.o: main.cc auxlib.h stringset.h astree.h lyutils.h yyparse.h
yylex.o: yylex.cc auxlib.h lyutils.h astree.h yyparse.h
yyparse.o: yyparse.cc lyutils.h astree.h auxlib.h yyparse.h
